class ERROR_ID:
    """
    Custom errors identifiers
    """
    NO_ERROR = 0
    ERROR_NOT_SUPPORTED = 100
    ERROR_NOT_IMPLEMENTED = 101
    INCORRECT_LOCALE_VALUE = 102
    ERROR_RECEIVING_DATA = 103
    ERROR_SENDING_DATA = 104
    ERROR_CURSOR_ALREADY_CLOSED = 105
    ERROR_NO_ACTIVE_QUERY = 106
    ERROR_CONNECTION_OPENED = 107
    ERROR_CONNECTION_NOT_OPENED = 108
    ERROR_INVALID_SCHEMA_TYPE = 109
    ERROR_INVALID_LOB_TYPE = 110

