class DATA_TYPES:
    """
    Data types constants
    """
    UNSPECIFIED_SIZEOF = 0
    BYTE_SIZEOF = 1
    BOOL_SIZEOF = 1
    INT_SIZEOF = 4
    LONG_SIZEOF = 8
    OBJECT_SIZEOF = 8
    RESULTSET_SIZEOF = 4
    SHORT_SIZEOF = 2
    FLOAT_SIZEOF = 4
    DOUBLE_SIZEOF = 8
    DATE_SIZEOF = 6
    TIME_SIZEOF = 6
    DATETIME_SIZEOF = 14
    TIMESTAMP_SIZEOF = 12
    OID_SIZEOF = 8
    VARIABLE_STRING_SIZEOF = -1
